# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'Zenith' do
  use_frameworks!

  # Pods for FavoriteFood
    pod 'Alamofire'
    pod 'SwiftyJSON'

  # Pods for Firebase
    pod 'Firebase'
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'

end
